
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Mar 12 2026 00:13:16 +06 (Mar 11 2026 18:13:16 UTC)

// Verification Directory fv/alu 

module alu(A, B, opcode, result, carry);
  input [3:0] A, B;
  input [2:0] opcode;
  output [3:0] result;
  output carry;
  wire [3:0] A, B;
  wire [2:0] opcode;
  wire [3:0] result;
  wire carry;
  wire UNCONNECTED, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_28, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_52, n_65;
  wire n_66;
  TLATX1 carry_reg(.G (n_12), .D (n_52), .Q (carry), .QN (UNCONNECTED));
  OAI221X1 g1132__2398(.A0 (n_66), .A1 (n_42), .B0 (n_47), .B1 (n_49),
       .C0 (n_48), .Y (result[3]));
  MX2X1 g1133__5107(.A (n_41), .B (n_45), .S0 (opcode[0]), .Y (n_52));
  OAI221X1 g1138__6260(.A0 (n_66), .A1 (n_20), .B0 (n_34), .B1 (n_37),
       .C0 (n_35), .Y (result[1]));
  AOI21X1 g1135__4319(.A0 (n_46), .A1 (n_44), .B0 (n_36), .Y (n_49));
  AOI31X1 g1137__8428(.A0 (n_47), .A1 (n_46), .A2 (n_33), .B0 (n_17),
       .Y (n_48));
  OAI21XL g1136__5526(.A0 (n_7), .A1 (n_44), .B0 (n_8), .Y (n_45));
  OAI221X1 g1134__6783(.A0 (n_66), .A1 (n_31), .B0 (n_38), .B1 (n_32),
       .C0 (n_39), .Y (result[2]));
  XNOR2X1 g1143__3680(.A (n_47), .B (n_40), .Y (n_42));
  OAI21XL g1139__1617(.A0 (n_16), .A1 (n_40), .B0 (n_15), .Y (n_41));
  AOI31X1 g1142__2802(.A0 (n_38), .A1 (n_46), .A2 (n_14), .B0 (n_25),
       .Y (n_39));
  NOR2X1 g1149__1705(.A (n_36), .B (n_65), .Y (n_37));
  AOI31X1 g1145__5122(.A0 (n_26), .A1 (n_34), .A2 (n_46), .B0 (n_18),
       .Y (n_35));
  INVX1 g1141(.A (n_33), .Y (n_44));
  AOI21X1 g1140__8246(.A0 (n_46), .A1 (n_28), .B0 (n_36), .Y (n_32));
  OA21X1 g1147__7098(.A0 (n_24), .A1 (n_30), .B0 (n_22), .Y (n_40));
  XNOR2X1 g1150__6131(.A (n_38), .B (n_30), .Y (n_31));
  OAI221X1 g1146__1881(.A0 (n_1), .A1 (n_23), .B0 (n_19), .B1 (n_21),
       .C0 (n_13), .Y (result[0]));
  AOI21X1 g1144__5115(.A0 (n_6), .A1 (n_28), .B0 (n_5), .Y (n_33));
  OAI22X1 g1153__4733(.A0 (n_24), .A1 (n_23), .B0 (n_22), .B1 (n_21),
       .Y (n_25));
  XNOR2X1 g1154__6161(.A (n_19), .B (n_34), .Y (n_20));
  OAI22X1 g1155__9315(.A0 (n_10), .A1 (n_23), .B0 (n_9), .B1 (n_21), .Y
       (n_18));
  OAI22X1 g1156__9945(.A0 (n_16), .A1 (n_23), .B0 (n_15), .B1 (n_21),
       .Y (n_17));
  INVX1 g1148(.A (n_28), .Y (n_14));
  OAI22X1 g1157__2883(.A0 (n_12), .A1 (n_36), .B0 (n_2), .B1 (n_26), .Y
       (n_13));
  OA21X1 g1158__2346(.A0 (n_10), .A1 (n_19), .B0 (n_9), .Y (n_30));
  OAI21X1 g1151__1666(.A0 (n_26), .A1 (n_3), .B0 (n_4), .Y (n_28));
  NAND2BX1 g1161__6417(.AN (n_21), .B (opcode[0]), .Y (n_23));
  AND2X1 g1162__5477(.A (n_12), .B (opcode[0]), .Y (n_46));
  NOR2BX1 g1163__2398(.AN (n_8), .B (n_7), .Y (n_47));
  NOR2BX1 g1164__5107(.AN (n_6), .B (n_5), .Y (n_38));
  NOR2BX1 g1165__6260(.AN (n_4), .B (n_3), .Y (n_34));
  NOR3BX1 g1166__4319(.AN (opcode[2]), .B (opcode[1]), .C (opcode[0]),
       .Y (n_36));
  NAND2BX1 g1170__8428(.AN (A[3]), .B (B[3]), .Y (n_8));
  NOR2X1 g1167__5526(.A (B[1]), .B (A[1]), .Y (n_10));
  NOR2X1 g1182__6783(.A (B[3]), .B (A[3]), .Y (n_16));
  NAND2BX1 g1169__3680(.AN (A[2]), .B (B[2]), .Y (n_6));
  NOR2X1 g1180__1617(.A (B[2]), .B (A[2]), .Y (n_24));
  NOR2BX1 g1168__2802(.AN (A[3]), .B (B[3]), .Y (n_7));
  NOR2X1 g1184__1705(.A (opcode[1]), .B (opcode[2]), .Y (n_12));
  NOR2BX1 g1174__5122(.AN (B[0]), .B (A[0]), .Y (n_26));
  NAND2BX1 g1175__8246(.AN (opcode[2]), .B (opcode[1]), .Y (n_21));
  NOR2BX1 g1176__7098(.AN (A[0]), .B (B[0]), .Y (n_2));
  NOR2X1 g1177__6131(.A (B[0]), .B (A[0]), .Y (n_1));
  NAND2BX1 g1171__1881(.AN (B[1]), .B (A[1]), .Y (n_4));
  NOR2BX1 g1179__5115(.AN (A[2]), .B (B[2]), .Y (n_5));
  NAND2X1 g1178__7482(.A (B[3]), .B (A[3]), .Y (n_15));
  NAND2X1 g1172__4733(.A (B[1]), .B (A[1]), .Y (n_9));
  NOR2BX1 g1173__6161(.AN (B[1]), .B (A[1]), .Y (n_3));
  NAND2X1 g1181__9315(.A (B[2]), .B (A[2]), .Y (n_22));
  NAND2X1 g1183__9945(.A (B[0]), .B (A[0]), .Y (n_19));
  NOR2BX1 g2(.AN (n_46), .B (n_26), .Y (n_65));
  NAND2BX1 g1187(.AN (opcode[0]), .B (n_12), .Y (n_66));
endmodule

